const primaryColors = require("@left4code/tw-starter/dist/js/colors");

module.exports = {
    purge: [
        "./src/**/*.php",
        "./src/**/*.html",
        "./src/**/*.vue",
        "./resources/**/*.php",
        "./resources/**/*.html",
        "./node_modules/@left4code/tw-starter/**/*.js",
    ],
    darkMode: "class",
    theme: {
        borderColor: (theme) => ({
            ...theme("colors"),
            DEFAULT: primaryColors.gray["300"],
        }),
        extend: {
            colors: {
                ...primaryColors,
                theme: {
                    1: "#aa1c1c",
                    2: "#F1F5F8",
                    3: "#bb2e2e",
                    4: "#bc3131",
                    5: "#DEE7EF",
                    6: "#d32929",
                    7: "#743636",
                    8: "#D2DFEA",
                    9: "#91C714",
                    10: "#d83131",
                    11: "#F78B00",
                    12: "#FBC500",
                    13: "#7F9EB9",
                    14: "#E6F3FF",
                    15: "#8da9be",
                    16: "#966060",
                    17: "#FFEFD9",
                    18: "#D8F8BC",
                    19: "#af2424",
                    20: "#c13939",
                    21: "#C6D4FD",
                    22: "#E8EEFF",
                    23: "#9f1a1a",
                    24: "#911414",
                    25: "#ffc7c7",
                    26: "#9a1515",
                    27: "#ad2020",
                    28: "#fdbbbb",
                    29: "#b22828",
                    30: "#f59898",
                },
            },
            fontFamily: {
                roboto: ["Roboto"],
            },
            container: {
                center: true,
            },
            maxWidth: {
                "1/4": "25%",
                "1/2": "50%",
                "3/4": "75%",
            },
            screens: {
                sm: "640px",
                md: "768px",
                lg: "1024px",
                xl: "1280px",
                xxl: "1600px",
            },
            strokeWidth: {
                0.5: 0.5,
                1.5: 1.5,
                2.5: 2.5,
            },
        },
    },
    variants: {
        extend: {
            zIndex: ["responsive", "hover"],
            position: ["responsive", "hover"],
            padding: ["responsive", "last"],
            margin: ["responsive", "last"],
            borderWidth: ["responsive", "last"],
            backgroundColor: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
            borderColor: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
            textColor: ["last", "first", "odd", "responsive", "hover", "dark"],
            boxShadow: ["last", "first", "odd", "responsive", "hover", "dark"],
            borderOpacity: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
            backgroundOpacity: [
                "last",
                "first",
                "odd",
                "responsive",
                "hover",
                "dark",
            ],
        },
    },
};
